# Local synthetic fixtures. Text below and procedural music in quality.mjs are CC0.
# Speech audio is generated by the user's installed Windows voices, not redistributed.
$ErrorActionPreference = 'Stop'
Add-Type -AssemblyName System.Speech
New-Item -ItemType Directory -Force artifacts/fixtures | Out-Null
$fixtureRoot = (Resolve-Path artifacts/fixtures).Path
$synth = New-Object System.Speech.Synthesis.SpeechSynthesizer
$format = New-Object System.Speech.AudioFormat.SpeechAudioFormatInfo(48000, [System.Speech.AudioFormat.AudioBitsPerSample]::Sixteen, [System.Speech.AudioFormat.AudioChannel]::Mono)
$samples = @(
  @{ Name = 'english'; Voice = 'Microsoft Zira Desktop'; Text = 'Welcome back everyone. Today we are exploring a quiet village beside the river. Let me know what you think about the new game. I will explain the next step before we start.' },
  @{ Name = 'turkish'; Voice = 'Microsoft Tolga'; Text = 'Herkese merhaba, yayına hoş geldiniz. Bugün nehir kenarındaki küçük bir köyü keşfediyoruz. Yeni oyun hakkında ne düşündüğünüzü söyleyin. Başlamadan önce bir sonraki adımı açıklayacağım. Sesim net geliyor mu?' },
  @{ Name = 'second'; Voice = 'Microsoft Hazel Desktop'; Text = 'There is another player near the bridge. We should walk along the river and check the building on the right. I can see the entrance from here.' }
)
try {
  foreach ($sample in $samples) {
    $synth.SelectVoice($sample.Voice)
    $synth.SetOutputToWaveFile((Join-Path $fixtureRoot ($sample.Name + '.wav')), $format)
    $synth.Speak($sample.Text)
    $synth.SetOutputToNull()
  }
} finally { $synth.Dispose() }
